def condition():
    condition = ['management of congestive heart failure',
 'birth prevention',
 'menstrual cramps',
 'acid reflux',
 'fibromyalgia',
 'hair loss',
 'add',
 'depression',
 'panic disorder',
 'allergies',
 'bacterial vaginosis',
 'sparse eyelashes',
 'skin cancer',
 'anxiety',
 'nerve disorder',
 'sore throat ear infections',
 'generalized anxiety disorder',
 'psoriasis',
 'ezcema',
 'panic attacks and depression',
 'acne',
 'anti-aging, acne',
 'epilpsy',
 'multiple sclerosis',
 'asthma, emphysema',
 'bipolar disorder and depression',
 'fibromyalgia, failed back syndrome',
 'adhd',
 'osteoporosis',
 'fatigue',
 'insomnia',
 'male pattern baldness',
 'a typical migraines',
 'migraine headaches',
 'severe peridontal disease',
 'seizures,migraines,fibro.',
 'ed',
 'possible lymphoma/kidney pain',
 'seizure disorder',
 'post surgical pain',
 'broken collarbone',
 'high cholestoral',
 'basal cell carcinoma',
 'birth control',
 'treatment of acne',
 'replacement thearpy',
 'over weight',
 'stomach pain',
 'glaucoma',
 'sun damage & fine lines',
 'hypertension',
 'wrinkles',
 'mild depression',
 'high cholesterol',
 'anti-aging prophilatic',
 'depression/ anxiety',
 'auto accident, severe whiplash',
 'low thyroid levels',
 'hypothyroidism',
 'depression/anxiety',
 'heratburn',
 'a little bit of osteoporosis in the hips',
 'gerd',
 'tsh level was low no clinical symtoms',
 'anxiety/ pain',
 'menopause for 2 years, first hormone pill taken',
 'migraines',
 'depression and generalized anxiety',
 'pneumonia',
 'facial hair',
 'high colorestoral',
 'sore throat',
 'antiaging',
 'osteopenia',
 'fun',
 'discoloration',
 'cold sore/fever blister (herpes-simplex)',
 'menopause',
 'severe neck pain lasting 8-9 mons',
 'back injury',
 'pain',
 'ovarian cysts/sciatic nerve',
 'stop smoking aid',
 'surgical menopause',
 'anxiety/ ocpd /depression',
 'pain relief  from an infected cat bite wound',
 'high blood pressure',
 'erectile disfunction',
 'cholesterol slightly elevated',
 'hay fever, allergies',
 'congestion',
 'uti',
 'asthma',
 'fatigue not being able to get up in am',
 "tia's - anxiety",
 'major depression/anxiety',
 'periodontal surgery',
 'smoking',
 'ocd',
 'menstrual cramping',
 'ankylosing spondylitis',
 'kidney pain, difficult urination',
 'shoulder pain',
 'restless leg syndrome',
 'bronchial infection',
 'for  back pain',
 'cholesterol/high blood pressure',
 'stress',
 'arthritis',
 'severe acne',
 'chronic pain',
 'epididymitus',
 'weight loss',
 'back pain',
 'excessive fatigue',
 'birth control method',
 'epilepsy',
 'malaria prevention',
 'low under active thyroid',
 'nausea/vomiting',
 'hyperpigmentation, photoaging, mild hormonal acne',
 'tourette syndrome',
 'insomina',
 'rosacea',
 'high intraocular pressure (glaucoma)',
 'severe allergies',
 'nausea',
 'bipolar disorder',
 'diabetes',
 'slight loss of calcium in hip area',
 'eczema',
 'menopausal symptoms',
 'cystic acne on chin and jaw',
 'muscle spasms',
 'chronic tension headaches/ mild depression',
 'stop smoking',
 'bipolar 2',
 'acne/anti-agin',
 'severe sinus infection',
 'depression not resolved with antidepressant drugs',
 'sinusitis',
 'sinus infection',
 'inflamed neck muscles',
 'panic disorder, agoraphobia',
 'depression and anxiety',
 'adrenal burnout, chronic fatigue & premature agin',
 'hyperactive nerves and chronic small seizures',
 'total hist',
 'melasma, unevean skin tone, ocasionally pimples',
 'pre-surgery',
 'major sinus infection',
 'migraine',
 'postmenopausal vaginal atrophy',
 'regulate periods',
 'aging',
 'heartburn',
 'erectile dysfunction',
 'perepheral neuropathy',
 'insomnia - early awakening',
 'gout',
 'agitation management r/t lewy body syndrome  demen',
 'rhematory arthritis',
 'smoking cessation',
 'anxiety and to avoid feeling misrable',
 'arthritis/knee pain',
 'fungal growth on feet',
 'herniated disk in my lower back',
 'cold sores',
 'nerve damage',
 'panic attacks',
 'hysterectomy',
 'depression, lack of motivation',
 'anxiety/ mild depression',
 'sciatica',
 'tia type seizures, stress',
 'dark skin spots on face',
 'restless legs syndrome',
 'irregular menses',
 'weightloss',
 'shift work insomnia',
 'bipolar',
 'scar revision surgery',
 'high cholesterol and triglycerides (21.1!)',
 'contraception',
 'tooth abscess',
 'tonsillitis/strep throat',
 'restless sleep',
 'anxiety disorder',
 'hormonal imbalances and pregnancy prevention',
 'deep gum pockets',
 'opioid addiction',
 'clinical depression',
 'lingering infection - ear, sinus, throat',
 'metabolic syndrome x',
 'neuropathy back pain',
 'obsessive compulsive disorder',
 'sleep problem',
 'hot flashes',
 'pain after surgery',
 'rash',
 'pre-barrett (errosion of the esophagus)',
 'infection from grazing an ankle on coral',
 'mrsa skin infection',
 'swine flu',
 'psychosis',
 'breast cancer',
 'arthritis pain',
 'fibromylgia',
 'schizophrenia',
 'acute sinusitis/bronchitis',
 'pigmentation',
 'sever depression',
 'osteo arthritis',
 'razor bumps',
 'genital herpes',
 'fever blisters',
 'urinary tract infection',
 'infertility',
 'hot flash sleep problems',
 'chronic back pain',
 'depression, irritability',
 'dry eyes',
 'low thyroid',
 'post surgery',
 'severe depression',
 'major depression',
 'tension headaches',
 'depression/difficulty sleeping',
 'persistant migraines',
 'menopause, memory loss, night sweats, low libido',
 'pregnancy prevention',
 'depression/insomnia',
 'prostatitis (chronically)',
 'asthmatic bronchitis',
 'hypothyroid',
 'anxiety due to relationship stress',
 'gi irritation',
 'itchy and irritated skin',
 'dysthymia',
 'hair growth',
 'yeast infection',
 'fungus',
 'longer eyelashes',
 'i got my toothpulled',
 'acne, melasma',
 'possible uti',
 'bi-polar mania with anger issues',
 'anxiety insomnia',
 'depresson/anxiety',
 'severe headache',
 'focus',
 'fatigue / malaise due to infections',
 'tennis elbow',
 'seizure, hbp, cholesterol',
 'rosecea',
 'dizzyness,, vertigo, nausea,',
 'headache',
 'nasal allergy',
 'baldness',
 'hives',
 'allergic rhinitis',
 'ptsd/insomnia',
 'tachycardia',
 'fertility',
 'high cholesteral',
 'severe hives angiodema',
 'hairloss',
 'mild hypothyroidism',
 'recurring cold sores',
 'muscle pain/spasms - legs',
 'dystimia',
 'buldging/ruptured disc',
 'pentasa',
 'epidimytis',
 'strep throat',
 'pms',
 'herpes',
 'for allergic condition and there after begning of',
 'skin rash',
 'menopausal',
 'bipolar ii',
 'excess stomach acid.',
 'bph',
 'bipolar disorder / insomnia',
 'ovarian cyst',
 'depression/panic disorder',
 'incontinence',
 'neck and back pain/  whiplash',
 'viral bronchitis',
 'vertigo',
 'anxiety and depression',
 'hypothyroidism after thyroidectomy',
 'yeast diaper rash',
 'anxiety/depression',
 'nasal allergies',
 "crohn's with fistula in ano",
 'neuropathic pain aand fibromyalgia',
 'hypothryroid',
 'poor sleep quality',
 'hyperlipidemia',
 'hyperhidrosis',
 'swollen passages from allergies',
 'increase dopmaine levels',
 'ulcer',
 'depression; intrusive suicidal impulses',
 "baker's cysts behind both knees",
 'vaginal bacteria',
 'depression, ptsd fatigue',
 'short term memory loss',
 'acne, wrinkles',
 'chronic fatigue syndrome',
 'adult acne',
 'chronic cough and allergies',
 'puncture wound',
 'acne and contraception',
 'birth control, menstrual cramps',
 'anxiety, panic attck, nervousness',
 'skin damage',
 'peri-menopausal syptoms',
 'severe ulcerative colitis',
 'chronic neck/back pain, chronic tension headache',
 'bronchitis',
 'thinning hair',
 'irritability,anxiety',
 'persistent chest infection symptoms',
 'acne rosacea',
 'narcolepsy, fibromyalgia',
 'thyroid removal',
 'atrial fibrillation',
 'cold',
 'spastic bladder',
 'migraine relief',
 'hyper pigmentation, wrinkles',
 'ankle sprain',
 'anxiety, depression, panic attacks',
 'adult add',
 'adult adhd',
 'hypercholesterolemia',
 'elevated cholesterol',
 'for wrinkle (line) reduction',
 'chronic back pain/depression/anxiety',
 'skin infection',
 'have not stop bleeding',
 'bladder infections',
 'for epilepsy',
 'anxiety/panic attacks',
 'hepatitis b',
 'ibs',
 'primary hypersomnia',
 'chronic daily headache',
 'shortness of breath, itching all over',
 'photoaging',
 'restless leg sydrome',
 'sprained ankle',
 'sciatica pain/bulging discs',
 "crohn's disease",
 'after an angiogram',
 'social anxiety',
 'mucus in stool',
 'severe insomnia',
 'serious food poisoning, uti',
 'knee pain',
 'migraines/upper back pain',
 'bipolar disorder ii',
 'osteopenia and osteoporosis',
 'low energy and depression',
 'wrinkles around eyes',
 'pain, muscle strain',
 'shingles pain',
 'subungal hematoma',
 'atopic dernatitis',
 "raynaud's disease",
 'hormone replacement',
 'ingrown toenails',
 'depression with anxiety',
 'to help sleep',
 'post hemorrhoidectomy',
 'achilles tendonitis',
 'tooth infection',
 'anxiety/ depression',
 'bipolar i',
 'possible osteoporosis',
 'depression, anxiety, ocd, nausea',
 'hair regrowth',
 'dark spots',
 'trochanteric bursitis',
 'to quit smoking',
 'for treating wrinkles',
 'colestrol',
 'menstrual migraines',
 'bacterial infectoin',
 'tinea barbae',
 'acne/oily skin',
 'morning sickness/nausea',
 'insomnia, bipolar',
 'schizoaffective disorder',
 'stress, feeling overwhelmed',
 'uveitis, inflmmatory arhtiritis in hands',
 'bipolar disorder with severe lows & fatigue,',
 '2 compressed discs in neck',
 'pregnancy prevention, cycle regulation',
 'allegry',
 'gerd with laryngeal spasms',
 'fatique, depression',
 'pigmentatation',
 'dog bite prophylaxis',
 'nocturnal myoclonus (like restless leg syndrome)',
 'asthmas/ rhinitis',
 'pain/arthritis',
 'hormone and for prevention of osteoporosis',
 'type 2 diabetes',
 'cough',
 'major depressive disorder',
 'neural pain',
 'nerve damage from brachial plexitus',
 'delayed gastric emptying-nausea',
 'bacterial growth',
 'menopause symptoms',
 'rosacea/ acne',
 'unable to sleep because of pain',
 'acute sinusitis',
 'hair loss, receding hairline',
 'ac joint dislocation',
 'skin allergy',
 'muslce inflammation',
 'thyroid goiter',
 'esophogeal strictures',
 'post-surgical pain',
 'abcessed tooth',
 'nerve pain, fibromyalgia',
 'staphf infection',
 'insomnia, migraines',
 'rash on neck that spread to face',
 'bi-polar 2',
 'acute and long term chronic and severe back pain',
 'i took seasonique just  to prevent pregnancy',
 'reduce cholesterol',
 'rls',
 'anxiety depression',
 'chronic depression',
 'sggression, hyperactivity',
 'obesity',
 'bi-polar disorder',
 'vaginal dryness/bladder inflamation-irritations',
 'airplane flight anxiety',
 'cold / flu',
 'pain relief (glenohumeral instability correction)',
 'hypercholesterolemia w/ low ldl',
 'migraines-hormonal',
 'prostatitis',
 'sleep disorder',
 'overweight, self confidence',
 'overeating, weight gain',
 'high blood presure',
 'ulcerative colitis',
 'bone density tests showed early osteo.',
 'bipolar 2-extreme moods swings',
 'diarrhea',
 'yeast',
 'nasal polyps',
 'acne, photoaging',
 'spinal injury',
 'asthma - repeated chest infections',
 'headaches',
 'sleeping aid',
 'recurrent depression',
 'anti malarial',
 'pink eye',
 'seasonal allergies',
 'inflamation at the femoral nerve',
 'quit smoking',
 'm to f transformation',
 'flat warts',
 'ostheoporosis prevention',
 'cramps, birth control',
 'ptsd, bi-polar, anxiety',
 'cystic fibrosis',
 'menopausal symptoms - hot flashes, sleep disturban',
 'neck pain',
 'sinus problems',
 'controceptive; help with pmsd',
 'dvt',
 'toenail fungus',
 'vaginal dryness and urinary tract infections',
 'inner ear infection',
 'muscular pain - arm',
 'cystic acne',
 'fluid retention increased bp',
 'loss of bone mass',
 'muscle stiffness',
 'supra ventricular tachycardia',
 'mild arthritis in knees',
 'knee pain/inflamation',
 'broken ribs',
 'severe upper respitory tract infection',
 'anxiety, hopelessness',
 'eostrogen-positive breast cancer',
 'hrt hysterectomy',
 'migraine prevention',
 'refractory depression',
 'sever back pain,',
 'cold sore',
 'diabetese',
 'melasma',
 'sleep',
 'prevent pregnancy',
 'bi-polar',
 'prevent osteoporose',
 'anxiety, panic attack',
 'forehead frown lines',
 'sleeping problems',
 'asthma/copd',
 'respiratory infection',
 'acne - blackheads and acne scars',
 'muscle spasms (upper back/neck)',
 'perimenopause',
 'ra, sj�gren syndrome',
 'overweight',
 'menopausal symptoms, especially night sweats',
 'high c',
 'hypertention',
 'age spots on hand',
 'depression pain',
 'gastro esophageal reflux disease (gerd)',
 'gerd (gastroesophogeal reflux disease)',
 'infection in mandible',
 'inability to fall asleep',
 'irritable bowel syndrome',
 'allergy induced asthma',
 'sleeplessness',
 'appetite control',
 'std clamydia',
 'anti-depressant',
 'cold sores/fever blisters',
 'hyperpigmentation',
 'genitofemoral nerve damage',
 'skin correction',
 'acid reflux, gerd',
 'inflammatory arthritis',
 'low thyroid production',
 'to achieve a smoother skin surface',
 'rhuematoid arthritis',
 'heart burn',
 'sun damage to face',
 'cat bite',
 'roseasa',
 'cholesterol',
 'add & anxiety',
 'tension in jaw and bruxism (grinding of teeth)',
 'depression, axiety',
 'anxiety, ocd',
 'tonsilitis',
 'gad - generalised anxiety disorder.',
 'quitting smoking',
 'originally brain lesions then lower cholesterol',
 "gerd/barret's esophogus",
 'post surgery stomach pain',
 'mood swings, felt by- polar',
 'degenerative disc disorder, spinal stenosis l1-s1',
 'osteoporsis',
 'mild sedative',
 'tooth pain, root canal procedure',
 'extreme hot flashes',
 'pain relief after surgery',
 'u/i',
 'prevention of pregnancy/lighter periods',
 'ear infection',
 'facial',
 'agoraphobia, panic disorder',
 'chronic headaches',
 'prevent aging, improve skin',
 'mood',
 'pain - chronic panceatitis',
 'menopause - hrt',
 'allergy',
 'severe anxiety',
 'hysterectomy/menopause',
 'narcolepsy',
 'cold sore on side of face',
 'mild acne',
 'low energy',
 'skin aging',
 'pcos',
 'rhytids',
 'back pain/depression',
 'chest infection (viral)',
 'throat infection',
 'after birth thyroid not working to mormal levelc',
 'excessive coughing, later diagnosed as pneumonia',
 'all over and various type pain',
 'rheumatoid arthritis',
 'extrinsic aging',
 'panic attacks, depression',
 'acne on my back',
 'hair lose',
 'sleep problems',
 'seasonal allergy',
 'abdominal pain',
 'bipolar disorder type ii',
 'alcohol addiction',
 'migraine headache',
 'colitis',
 'gerd/acid reflux',
 'tempromandibular joint dysfunction (tmj)',
 'metabolic disorder',
 "crohn's",
 'blood clots',
 'irritated and sore throat,nose,eyes and sneezing.',
 'reflux',
 'ringworm/pityriasis',
 'cognitive enhancement',
 'high interoccular pressure',
 'acne and sun damage',
 'i was in a risk group - frontline pharmacist',
 'undiagnosed',
 'psoriatic arthritis',
 'post -surgery',
 'hay fever',
 'severe cold sores',
 'rhumitoid arthritis',
 'cocaine dependency',
 'bladder infection',
 'heartburn/gerd',
 'to lose 30 pounds',
 'budging disk in neck',
 'head injuries',
 'ldl cholesterol',
 'relapsing remitting ms, possible neuro sarcoidosis',
 'daily migraines 2-3 times a day',
 'chronic bronch/asthma',
 'itching/psosiasis',
 'adhd (attention deficit hyperactive disorder)',
 'atrial frbulation',
 'allergies sneezing , watery runny nose',
 'glucoma',
 'fungal toenails',
 'tuberculosis',
 'pain in my legs',
 'high colesteral',
 'a boil',
 'anxiety rapid onset',
 'cure for acne',
 'hgh deficiency & hiv',
 'vaginal eczema',
 'acid reflex',
 'perimenopause symptoms',
 'anxiety/trouble sleeping',
 'prevent menstral migranes',
 "can't sleep",
 'lower back pain',
 'cholesterol problems',
 'muscle pain and stiffness due to fibromyalgia',
 'mulitple sclerosis',
 'memory',
 'cat bite infection',
 'wakefulness -- difficulty falling back asleep',
 'perennial rhinitis',
 'progesterone balance',
 'narcalepsy',
 'clearing skin',
 'sinus infections/constant mucus & post nasal drip',
 'depression-anxiety',
 'aging skin',
 'severe knee pain',
 'sun damage removal',
 'tendinatis',
 'diabetes type 2',
 'major depressive disorder/ anxiety',
 'whiteheads',
 'obesity and diabetes',
 'skin warts on elbow',
 'anxety / depression',
 'minor insomnia',
 'acne/wrinkles',
 'birthcontrol',
 'initially, acne; later, anti-wrinkle',
 'mood stabilizer taken w/ prozac',
 'insomnia, headaches',
 'ptsd',
 'heart condition',
 'chronic musculoskeletal pain (neck/back)',
 'poor sleep with frequent wakefulness',
 'post surgery extreme pain',
 'sleep aid',
 'loss of bone density in spine',
 'mrsa abcess',
 'no more period',
 'post cosmetic surgery complications',
 'shift disorder',
 'jaw abscess',
 'vaginal dryness',
 'chronic pain (neck and migraines)',
 'constant coughing due to mucous',
 'anxiety/insomnia',
 'blood pressure',
 'coldsores',
 'depression/ cfs',
 'thyroid',
 'shingles',
 'sinus infections',
 'neck and back pain',
 'anti-inflammatory/pain',
 'infected throat and lung',
 "hashimoto's hypothyroidism",
 'acne and perioral dermatitis',
 'itching',
 'cold sore, fever blister',
 'hyperpigmatation',
 'urinary tract infrection',
 'chest infection',
 'migraine in assoc /w upper resp infection',
 'depression & anxiety',
 'severe recurrent sinus infections',
 'high cholestrol',
 'swine flu like illness in a pandemic',
 "conn's syndrome",
 'chronic sinusitis',
 'add - mild depression',
 'actinic keratoses',
 'hot flashes, depression',
 'difficulty sleeping',
 'lupus',
 'vaginal yeast infection',
 'acne and water retention',
 'type ii diabetes mellitus',
 'depression, anxiety',
 'conjunctivitus',
 'rare kidney infection',
 'acne and anti age benefits',
 'pain relief for arthritis and sleep aid',
 'chronic urinary and yeast infections due to drynes',
 'atrial fib',
 'skin spots',
 'anti-rejection',
 'pre cancer cells',
 'chronic sinus congestion',
 'vaginal dryness, night sweats',
 'microprolactinoma (benign pituitary tumour)',
 'adult moderate hormone related acne',
 'glandular fever',
 'teeth extractions',
 'menopause/hysterectomy',
 'mitral  valve prolapse',
 'severe performance anxiety',
 'hand dermatitis',
 'anxiety/worry',
 'improvement of skin appearance, very very mild acn',
 'opiate/heroin addiction',
 'ankylosing spondalytis',
 'preventing pregnancy',
 'neck and hip pain',
 'environmental allergies',
 'scar revision',
 'bipolar mania',
 'migrain',
 'attention deficit disorder (inattentive type)',
 'chronic pelvic pain',
 'underactive thyroid',
 'sinus allergy',
 'high cholestral',
 'daytime drowsiness',
 'poison ivy',
 'molar extraction',
 'hormonal acne',
 'conjunctivitis',
 'rosecea on the face',
 'high blood pressue --  diuretic',
 'pneumonia with associated cough',
 'facial skin',
 'surgery recovery',
 'skin agind, sun damage',
 'weight',
 'earache/sinusitis',
 'capsuar contracture of breast implant',
 'problems with my prostate',
 'o increase length and fullness of eyelashes',
 'scoliosis',
 'i kept getting pregnant. no more stairs.... please',
 'severe stomach pains, dizziness',
 'facial acne',
 'runny nose/ allergies',
 'heart',
 'dermatitis herpetiformis',
 'aging skin, few break-outs, hyperpigmentation',
 'athletes foot',
 'acne and birth control',
 'klebsiella pneumonia infection',
 'chronic pain from degenerative lumbar disc disease',
 'sleep disorder/anxiety',
 'r/a',
 'allergy, runny nose, hay fever',
 'prostate procedure',
 'problem staying asleep',
 'depression and anxiety.',
 'qit smoking',
 'opiod addiction',
 'cornea transplant rejection',
 'inattention  and disorganization',
 'low back pain, radiating to left leg',
 'hypertension/high blood pressure',
 'depression/anxiety/ptsd',
 'elevated glucose',
 'pain after dental surgery',
 'dermatitis',
 'panic attack and anxiety',
 'indigestion',
 'hypthyroidsim',
 'skin probles - acne, balckheads',
 'pinched nerve from bulging disc & disseminated pai',
 'bipolar/raciness/insomnia',
 'addh',
 'pain from broken arm',
 'simple partial seizure',
 'back stiffness',
 "hypothyriodism--hashimoto's thyroiditis",
 'borderline personality disorder, bi polar',
 'sinus infection with smelly nasal discharge',
 'anxiety/mild ptsd',
 'tension and anxiety',
 'diabetes type ii',
 'illiotibital tibital syndrom',
 'cluster headache',
 'gonorrhea',
 'chest infections',
 'sore throat/dryness',
 'insomnia due to peri-menopause',
 'r.a.',
 'burning feeling in throat and chest',
 'staph infection',
 'lower back pain and migraine',
 'toe nail fungus',
 'cervical spondylosis',
 'post menapause symptoms',
 'performance anxiety / social anxiety',
 'nerve condition, burning in legs and aching feet',
 'early onset osteoporosis',
 'severe headaches',
 'neuropathic pain from botched surgery',
 'perenniel rhinitis',
 'palpitations',
 'hyperpigmentation all over face',
 'bipolar depression',
 'ulcerative cholitis',
 'anxiety, depression',
 'originally sleep apnea',
 'severe pain',
 'essential tremor',
 'strokes',
 'juvenile idiopathic arthritis',
 'none',
 'gastrointestinal disorder',
 'family flu outbreak',
 'contraceptive',
 'male pattern hair loss',
 'sever muscle spasms lower back',
 'facial hyperpigmentation',
 'wrinkles, furrows',
 'migaine/tension headches',
 'not sleeping',
 'facial lines',
 'atypical breast biopsy',
 'smoking ceasation',
 'post partum anxiety/ depression',
 'allergic reaction',
 'neck & arm muscle spasms',
 'redness',
 'pmd',
 'candida caused yeast infection',
 'ibs/anxiety',
 'acute peptic ulcer',
 'rashes',
 'asthma flares',
 'attention deficit disorder',
 'high lpa',
 'collar bone injury',
 'hrt',
 'sun damage to skin',
 'complete hysterectomy',
 'tinnitus',
 'schizo-affective disorder',
 'replacement of femoral vein in leg',
 'pain/headaches',
 'anxiety/insomnia/',
 'hepatitis c',
 'cesarean',
 'insomnia, anxiety',
 'crohns disease',
 'endometrial hyperplasia',
 'eyelash growth',
 'acne, anti-aging',
 'indoor allergies',
 'aging wrinkles',
 'heavy menses',
 'cold chills and hot flashes',
 'chronic insomnia',
 'high blood pressure and',
 'nummular eczema',
 'sle (lupus), rheumatoid arthritis',
 'birth control pill',
 'tachacarrdia  rapid heartbeat',
 'irritable bowel syndrom',
 'hard time getting asleep',
 'maigrains',
 'estrogen replacement therapy',
 'hot flashes, headaches, fatigue, dry vagina',
 'anti aging',
 'irregularity/no babies!',
 'eye infection',
 'pain management',
 'add and depression',
 'interstitial cystitis',
 'congestive heart failure and edema',
 'neck/shoulder spasms',
 'muscle strain',
 'erictile dysfunction',
 'infection',
 'possible pertusis',
 'ptsd, anxiety, depprssion, obsessive remembering',
 'peripheral neuropathy',
 'alopecia',
 'sleep deprivation',
 'depression;',
 'temporary anxiety',
 'birth control. prevention of pregnacy',
 'depression, anxiety & pain',
 'high blood preasure',
 'adult onset acne',
 'memopause',
 "behcet's disease",
 'fungus on big toes',
 'herpes cold sores around mouth and nose',
 'skin exema',
 'hot flashes / night sweats',
 'anxiety, panic disorder',
 'cosmetic longer lashes',
 'arthritis in knees',
 'migranes',
 'ballanitis',
 'severe non-allergic bronchitis and cough',
 'restless legs',
 'diet',
 'systemic fungus',
 'depression, social anxiety disorder',
 'mastitis',
 'preventing malaria',
 'arthritis pain, neck injury',
 'shooting nerve-type pain in legs/fibromyalgia',
 'general depression/perimenopause',
 'dust allergy',
 'chronic leg pain due to trauma & surgeries',
 'improvement of skin appearance/health',
 'anti-malarial',
 'polinoidal cyst',
 'allergies and asthma',
 'acne / blackheads / oily skin',
 'hbp',
 'asthma/allergies',
 'ear and throat infection',
 'loss of bone density',
 'water in ear',
 'bursitis',
 "crohn's/colitis",
 'fingernail fungus',
 'oral surgery',
 'heart murmur/dental procedures',
 'repair and prevent wrinkles',
 'post breast cancer',
 'fine lines around eyes and mouth. between the brow',
 'aging skin, wrinkles, sag',
 'mania',
 'chronic tension headache',
 'tonic clonic seizures',
 'juvenile rheumatoid arthritis',
 'acic reflux',
 'upper respiratory infection on vacation',
 'perioral dermatitis',
 'post herpatic neuralga',
 'hot flashes, unable to sleep',
 'fine lines',
 'depression, fatigue',
 'pain from pinched nerve',
 'hot flashes/ over all feel better',
 'high cholesteol',
 'birth control, acne control',
 'seizure-1st and only at age 41',
 'osteoporosis/bone stength',
 'depresion anxiety obsessive behavior',
 'vaginal dryness, menopausal symptoms',
 'contact dermatitis',
 'brown spots',
 'rheumatiod arthritis',
 'total hysterectomy',
 'lose weight',
 'pocs, elevated testosterone, hirsutism',
 'mytral valve prolapse',
 'nerves, depression',
 'lower respiratory tract infection',
 'serious acne',
 'cold sores/ herpes i',
 'add inattentive, delayed sleep phase syndrome']
 
    return condition
